name: Deploy to Render

on:
  push:
    branches:
      - main # or the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-streamlit-app:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-streamlit-app:latest

    - name: Deploy to Render
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
             -H "Authorization: Bearer $RENDER_TOKEN" \
             -H "Content-Type: application/json" \
             -d '{}'
